version: "3.9"
services:

  jenkins:
    # default ports 8080, 50000 - expose mapping as needed to host
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: cicd-jenkins
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "50000:50000"
    environment:
      # Uncomment JENKINS_OPTS to add prefix: e.g. https://127.0.0.1:8443/jenkins
      #- JENKINS_OPTS="--prefix=/jenkins"
      - JENKINS_UID=${JENKINS_UID}
      - JENKINS_GID=${JENKINS_GID}
    volumes:
      - ${JENKINS_LOCAL_HOME}:/var/jenkins_home
      - ${HOST_DOCKER_SOCK}:/var/run/docker.sock

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: cicd-nginx
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - ${JENKINS_LOCAL_HOME}:/var/jenkins_home
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx

networks:
  jenkins:
    name: cicd-jenkins
    driver: bridge